<a href="https://colab.research.google.com/github/dpkeee/Udacity_DeepLearning_Nanodegree/blob/master/Dog%20Breed%20Classifer%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torchvision.models as models

# define VGG16 model
VGG16 = models.vgg16(pretrained=True)

# check if CUDA is available
use_cuda = torch.cuda.is_available()

# move model to GPU if CUDA is available
if use_cuda:
    VGG16 = VGG16.cuda()

Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/checkpoints/vgg16-397923af.pth


In [0]:
from PIL import Image
import torchvision.transforms as transforms
from torchvision import datasets


In [0]:
import cv2
org_img = cv2.imread('test.jpg')
rgb_img   = cv2.cvtColor(org_img, cv2.COLOR_BGR2RGB)
transform = transforms.Compose([transforms.RandomResizedCrop(224), 
                                      transforms.ToTensor(),
                                      transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                      std=[0.229, 0.224, 0.225]) ])
    
image_tensor = transform(rgb_img) 


TypeError: ignored

In [0]:
type(rgb_img)

numpy.ndarray

In [0]:
from PIL import Image
img = Image.open("test.jpg")


In [0]:
transform = transforms.Compose([transforms.RandomResizedCrop(224), 
                                      transforms.ToTensor(),
                                      transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                      std=[0.229, 0.224, 0.225]) ])
    
image_tensor = transform(img) 

In [0]:
image_tensor.shape

torch.Size([3, 224, 224])

In [0]:
VGG16.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [0]:
batch_t = torch.unsqueeze(image_tensor, 0)


In [0]:
batch_t.shape

torch.Size([1, 3, 224, 224])

In [0]:
VGG16.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [0]:
output = VGG16(batch_t)

In [0]:
print(output.shape)

torch.Size([1, 1000])


In [0]:
a= torch.argmax(output, dim=1).detach().numpy()

In [0]:
a= torch.argmax(output, dim=1)

In [0]:
a


array([252])

In [0]:
y = 0
print(a)
if a>=151 and a<=268:
   y = 1
print(y)

[252]
1


In [0]:

with open('imagenet_classes.txt') as f:
  labels = f.readlines()


In [0]:
labels[252]

" 252: 'affenpinscher, monkey pinscher, monkey dog',\n"

In [0]:
if  a >= 151 and a <= 268:
  print('yes its a dog')


yes its a dog


In [0]:
b = [1,2,3,4,5]

In [0]:
len(b)

5

In [0]:
range(len(b))

range(0, 5)

In [0]:
idx = VGG16_predict(img_path)
    
    return idx >= 151 and idx <= 268

In [0]:
img_path = "test.jpg"
from PIL import Image
import torchvision.transforms as transforms
from torchvision import datasets

def VGG16_predict(img_path):
  img = Image.open(img_path)
  transform = transforms.Compose([transforms.RandomResizedCrop(224), 
                                      transforms.ToTensor(),
                                      transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                      std=[0.229, 0.224, 0.225]) ])
    
  image_tensor = transform(img) 
  batch_t = torch.unsqueeze(image_tensor, 0)
  VGG16.eval()
  output = VGG16(batch_t)
  output_idx= torch.argmax(output,dim=1)
  print(output_idx)
  return output_idx



In [0]:
def dog_detector(img_path):
    ## TODO: Complete the function.
    detection = VGG16_predict(img_path)
    
    return detection >= 151 and detection <= 268

In [0]:
dog_detector(img_path)
    


tensor([862], grad_fn=<NotImplemented>)


tensor([False])